version: '2'

services:
  dockercachingsample:
    image: user/dockercachingsample${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
  rediscache:
    image: redis